const SYNONYMS = {
  // Common aliases
  "lactic acid": "lactate",
  "l-lactic acid": "lactate",
  "d-glucose": "glucose",
  "glc": "glucose",
  "g6p": "glucose-6-phosphate",
  "f6p": "fructose-6-phosphate",
  "f16bp": "fructose-1,6-bisphosphate",
  "g3p": "glyceraldehyde-3-phosphate",
  "gap": "glyceraldehyde-3-phosphate",
  "dhap": "dihydroxyacetone phosphate",
  "3pg": "3-phosphoglycerate",
  "2pg": "2-phosphoglycerate",
  "pep": "phosphoenolpyruvate",
  "pyr": "pyruvate",
  "pyruvic acid": "pyruvate",
  "lac": "lactate",

  // TCA
  "citric acid": "citrate",
  "isocitric acid": "isocitrate",
  "akg": "alpha-ketoglutarate",
  "2-oxoglutarate": "alpha-ketoglutarate",
  "succinic acid": "succinate",
  "fumaric acid": "fumarate",
  "malic acid": "malate",
  "oaa": "oxaloacetate",
  "acoa": "acetyl-coa",

  // Amino acids (one-letter codes)
  "a": "alanine",
  "r": "arginine",
  "n": "asparagine",
  "d": "aspartate",
  "c": "cysteine",
  "e": "glutamate",
  "q": "glutamine",
  "g": "glycine",
  "h": "histidine",
  "i": "isoleucine",
  "l": "leucine",
  "k": "lysine",
  "m": "methionine",
  "f": "phenylalanine",
  "p": "proline",
  "s": "serine",
  "t": "threonine",
  "w": "tryptophan",
  "y": "tyrosine",
  "v": "valine",

  // Three-letter codes
  "ala": "alanine",
  "arg": "arginine",
  "asn": "asparagine",
  "asp": "aspartate",
  "cys": "cysteine",
  "glu": "glutamate",
  "gln": "glutamine",
  "gly": "glycine",
  "his": "histidine",
  "ile": "isoleucine",
  "leu": "leucine",
  "lys": "lysine",
  "met": "methionine",
  "phe": "phenylalanine",
  "pro": "proline",
  "ser": "serine",
  "thr": "threonine",
  "trp": "tryptophan",
  "tyr": "tyrosine",
  "val": "valine",

  // Lipids
  "c0": "carnitine",
  "c2": "acetylcarnitine",
  "c3": "propionylcarnitine",
  "c4": "butyrylcarnitine",
  "c6": "hexanoylcarnitine",
  "c8": "octanoylcarnitine",
  "c10": "decanoylcarnitine",
  "c12": "lauroylcarnitine",
  "c14": "myristoylcarnitine",
  "c16": "palmitoylcarnitine",
  "c18": "stearoylcarnitine",
  "c18:1": "oleoylcarnitine",
  "free carnitine": "carnitine",
  "l-carnitine": "carnitine",
  "palmitic acid": "palmitate",
  "oleic acid": "oleate",
  "stearic acid": "stearate",
  "linoleic acid": "linoleate",
  "arachidonic acid": "arachidonate",
  "epa": "eicosapentaenoate",
  "dha": "docosahexaenoate",

  // Ketones
  "bhb": "beta-hydroxybutyrate",
  "3-hydroxybutyrate": "beta-hydroxybutyrate",
  "3hb": "beta-hydroxybutyrate",
  "acac": "acetoacetate",

  // Nucleotides
  "adenosine triphosphate": "atp",
  "adenosine diphosphate": "adp",
  "adenosine monophosphate": "amp",
  "guanosine triphosphate": "gtp",

  // Microbial
  "tma": "trimethylamine",
  "tmao": "trimethylamine n-oxide",

  // Redox
  "gsh": "glutathione",
  "gssg": "glutathione disulfide",
  "coq10": "coenzyme q10",
  "ubiquinone": "coenzyme q10",

  // Vitamins
  "vitamin e": "alpha-tocopherol",
  "vitamin c": "ascorbate",
  "vitamin a": "retinol",
  "vitamin d": "25-hydroxyvitamin d",
  "25-oh-d": "25-hydroxyvitamin d",
  "vitamin b1": "thiamine",
  "vitamin b2": "riboflavin",
  "vitamin b6": "pyridoxine",
  "vitamin b9": "folate",
  "folic acid": "folate",
  "vitamin b12": "cobalamin",

  // Other
  "5-ht": "serotonin",
  "5-hydroxytryptamine": "serotonin",
  "da": "dopamine",
  "gamma-aminobutyric acid": "gaba",
  "hcy": "homocysteine",
  "orn": "ornithine",
  "cit": "citrulline",
  "urate": "uric acid",
};

export default SYNONYMS;
